### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by slawmalcz** [slawmalcz/GWP-Proj#5]
Ustalenie aktualnego postępu prac. Sprawdzenie standardu kodu, oraz ustalenia następnych kroków.

**Comment by damian19dk** [comment]
Proszę Cię bardzo, dodam na początku coś od siebie:
Trochę męczyłem się z samym odpaleniem projektu, bo chciałem zobaczyć, jak będzie działać na moim lapku i jak na komputerze wydziałowym. Wyniki były takie, że z brancha Develop w trybie Debug Win32 i mój lapek i wydziałowy poległ xd Na wydziałowym wywala kosmiczny błąd fghGenBuffers is null (który co ciekawe zdarza się niektórym przy odpalaniu zdalnym albo przy wirtaulnej maszynie), na moim pluje się o funkcję convertToModel, bo następuje jakieś "naruszenie pamięci". W trybie Release wszystko śmiga jak miło na moim lapku, na wydziałowym ten sam dziwny błąd. A teraz do rzeczy:

a) Widzę, że kod mamy prawie cały zapożyczony od Pałubickiego, ale to dobrze, bo jeszcze doczepiłby się, że korzystamy z technologii, których on nie ujął w zaleceniach
b) Bardzo fajny pomysł z menu, nie trzeba crashować aplikacji przy każdym wyłączeniu, to dostosowywanie kamery może być ciekawe, ale nie ocenię, póki nie zobaczę w akcji (czytaj pkt następny)
c) Z początku myślałem, że mi karta graficzna zwariowała do reszty, bo pusta scena, ale potem sobie uświadomiłem, że nie ma folderu models i plików .obj, więc co się dziwić, że pusto :)
d) Przytwierdziłeś już kamerę do ryby, rysujesz tekstury dla podłoża i ryby
e) Model Phonga "praktycznie" jest zaimplementowany w shaderach
f) Mamy także ustawione światło kierunkowe
g) NIby to glFrustum uznaje się za depracated, ale możliwości takie same jak gluPerspective, więc to tylko taka uwaga wyczytana z forum

Moja ogólna ocena wygląda tak, że odwaliłeś kawał dobrej roboty. I naprawdę proponuję jakoś podzielić się obowiązkami, bo wyjdzie na to, że nic nie robię przy tym projekcie, a bycie uznanym za piąte koło u wozu to dla mnie brzmi jak obelga xd Żeby nie okazało się, że oboje będziemy pracować nad tym samym w tym samym czasie - to byłaby strata czasu.

**Comment by slawmalcz** [comment]
OK do zrobienia jest nastepny sprint to co chcesz zrobic daj sobie jako assign i bede wiedzial co ty robisz.
Ja weje okolo 19 i reszte przypisze sobie.

**Comment by damian19dk** [comment]
Dobra, zaczekam z właściwą produkcją, jak wrzucisz wszystko co aktualnie masz na Githuba. Chyba, że to już wszystko, to daj znać.
